"""Domínio oficial de arranjos de pagamento da CERC.

Fonte: "arranjos_pagamento_cerc.xlsx" (2026-08-28) — mesma fonte usada em
`ap-front/src/data/arranjosCerc.ts`. 47 códigos + o curinga `99T` (todos),
que é convenção interna deste sistema (SPEC-01 §2.3), não um código CERC.
"""

ARRANJOS_CERC = [
    ("BCD", "Banescard Cartão de Débito"),
    ("HCD", "Hiper Débito"),
    ("NUD", "NuPay Débito"),
    ("VCD", "Visa Cartão de Débito"),
    ("ACD", "Amex Débito"),
    ("CBD", "Cabal Débito"),
    ("SCD", "Sorocred Cartão de Débito"),
    ("ECD", "Elo Cartão de Débito"),
    ("BVV", "Ben Visa Vale"),
    ("MCD", "Mastercard Cartão de Débito"),
    ("OCD", "Ourocard Cartão de Débito"),
    ("SPC", "Sem Parar"),
    ("FRC", "Fortbrasil"),
    ("VCB", "Visa Cartão Benefícios"),
    ("CUP", "Cup Crédito"),
    ("ECC", "Elo Cartão de Crédito"),
    ("MXC", "Maxifrota"),
    ("VDC", "Verdecard Cartão de Crédito"),
    ("CSC", "Credi-Shop"),
    ("ECB", "Elo Cartão Benefícios"),
    ("CZC", "CREDZ Crédito"),
    ("JCC", "JCB Cartão de Crédito"),
    ("SCC", "Sorocred Cartão de Crédito"),
    ("NUC", "NuPay Crédito"),
    ("BCC", "Banescard Cartão de Crédito"),
    ("BRC", "Brasil Card"),
    ("GCC", "Goodcard Crédito"),
    ("DAC", "Dacasa"),
    ("SFC", "Senff"),
    ("CCD", "Calcard"),
    ("MAC", "Mais!"),
    ("BNC", "Banese Card"),
    ("HCC", "Hipercard Cartão de Crédito"),
    ("ALC", "Alelo Credito Pós"),
    ("MCB", "Mastercard Cartão Benefícios"),
    ("AUC", "Aura"),
    ("DCC", "Liquidações de transações transfronteiriças Diners"),
    ("AVC", "Avista"),
    ("RCC", "Redesplan"),
    ("CAC", "Cielo Amex Crédito"),
    ("VCC", "Visa Cartão de Crédito"),
    ("AGC", "Agiplan"),
    ("TKC", "TicketLog Pós"),
    ("CBC", "Cabal Crédito"),
    ("MCC", "Mastercard Cartão de Crédito"),
    ("ACC", "Amex Cartão de Crédito"),
    ("DBC", "Discover"),
]
